---
title: "Peru D. gigas case study"
author: "JGM"
date: "2023-04-03"
output: html_document
---

```{r setup, include=FALSE}
library (tidyverse)
library (stringr)

# function for converting catch in mt to children fed ----
# this will also bring in fishnutr data and RNI data
source ("Scripts/Function_convert_catch_amt_children_fed.R")

# SAU data ----

# as of 10/25/22 just 2019 data, suggested by Deng Palomares. Clipped in SAU_explore.R
sau_2019 <- readRDS("Data/SAU_2019.Rds")

# or mean of most recent 5 years *doesn't currently include indonesia* 
sau_2015_2019 <- readRDS("Data/SAU_2015_2019.Rds")


# exports ARTIS ----
# emailed 10 19 2022
exports <- read_csv ("Data/20221019_edf_ARTIS_snet.csv")

# take a five year mean of proportion exported
exports_5yr_mean <- exports %>%
  filter (between (year, 2015, 2019)) %>%
  group_by (exporter_iso3c, sciname) %>%
  summarise (mn_prop_exp = mean (exports_percent_of_prod, na.rm = TRUE)/100) %>%
  ungroup() %>%
  mutate (species = str_to_sentence(sciname),
          # just doing country names by hand...
          country = case_when (
            exporter_iso3c == "CHL" ~ "Chile",
            exporter_iso3c == "IDN" ~ "Indonesia",
            exporter_iso3c == "PER" ~ "Peru", 
            exporter_iso3c == "MEX" ~ "Mexico",
            exporter_iso3c == "SLE" ~ "Sierra Leone"
          ), .keep = "unused") 

# expressed as catch ratios relative to base year for midcentury and end century, can multiply by landings
catch_upside_relative <- readRDS("Data/nutricast_upside_relative.Rds")
```

# nutrient content
```{r print_nutrient_content}
compiled_nutr %>% 
  filter (species == "Dosidicus gigas") %>%
  left_join(rni_child, by = "nutrient") %>%
  mutate (perc_rni = amount/RNI * 100) %>%
  arrange (desc (perc_rni))
```
```{r peru_inadequate_intake}
# this is already in percent, don't multiply by 100
pii <- read_csv ("Data/Beal_2017_SI_inadequate_micronutrients.csv")

peru_pii <- pii %>% 
  filter (Country == "Peru", Year == 2011) %>%
  select (Fortification, Micronutrient, `Prevalence of Inadequate Intake`) 


peru_pii %>%
  arrange (desc (round(`Prevalence of Inadequate Intake`, 2)))


```
```{r compare_radar_barchart}
library (ggradar)


spp_rni_met <- compiled_nutr %>%
  filter (species %in% c("Dosidicus gigas", "Engraulis ringens", "Trachurus murphyi", "Merluccius gayi peruanus")) %>%
  # join to rni data
  left_join (rni_child, by = "nutrient") %>%
  
  # this would be the percentage of your daily requirement you could get from a 100g serving of each species. cap at 100%
  mutate (perc_rni = amount/RNI * 100,
          perc_rni = ifelse (perc_rni > 100, 100, perc_rni),
          nutrient = 
            case_when (nutrient == "Vitamin_A" ~ "Vit A",
                       nutrient == "Omega_3" ~ "Omg 3",
                       TRUE ~ nutrient)) %>%
  ungroup()


nutr_radar_plot <- spp_rni_met  %>%
  # filter (species %in% c("Engraulis ringens", "Trachurus murphyi", "Merluccius gayi gayi"), !nutrient %in% c("Protein", "Selenium")) %>%
   mutate(
      spp_short = ifelse (
        grepl(" ", species),
        paste0 (substr(species, 1, 1), ". ", str_split_fixed (species, " ", 2)[,2]),
        species)) %>%
  select (spp_short, nutrient, perc_rni) %>%
  pivot_wider (
    names_from = nutrient,
    values_from = perc_rni) 


#png ("Figures/Squid_radar.png", res = 300, width = 5, height = 5, units = "in")  
ggradar(nutr_radar_plot,
        grid.min = 0, grid.max = 100, 
        group.point.size = 2,
        group.line.width = 1,
        legend.text.size = 8,
        axis.label.size = 4,
        grid.label.size = 4,
        legend.position = "bottom") +
  
  theme (plot.title = element_text (size = 14))
#dev.off()

png ("Figures/Squid_nutr_dodge_bar_sm.png", width = 7, height = 4, units = "in", res = 300)
 spp_rni_met  %>%
   filter (!nutrient %in% c("Protein", "Selenium")) %>%
    group_by (species) %>%
    mutate (micronutrient_density = sum (perc_rni),
            spp_short = ifelse (
              grepl(" ", species),
              paste0 (substr(species, 1, 1), ". ", str_split_fixed (species, " ", 2)[,2]),
              species)
    ) %>%
    ungroup() %>%
    
    ggplot (aes (x = reorder(spp_short, -micronutrient_density), fill = nutrient, y = perc_rni)) +
    geom_col (position = "dodge") +
    theme_bw() +
    labs (x = "", y = "% Child RNI met per 100g serving", fill = "Nutrient") +
    #ylim (c(0,100)) +
    ggtitle ("Nutrient content of selected species") +
    theme ( 
      axis.text.y = element_text (size = 13),
      axis.text.x = element_text (size = 11),
      axis.title = element_text (size = 16),
      strip.text = element_text(size = 16),
      legend.text = element_text (size = 12),
      legend.title = element_text (size = 14),
      plot.title = element_text (size = 18))
 dev.off()

```
```{r catch rnis}

# just pota for Peru, 2019
  pota_catch <- sau_2019 %>% filter (country == "Peru", fishing_entity == "Peru", species == "Dosidicus gigas") %>%
    group_by (species) %>% summarise (tonnes = sum (tonnes))
  
  pota_2019 <- calc_children_fed_func(species = "Dosidicus gigas", amount = pota_catch$tonnes, country = "Peru")
  
  png ("Figures/Peru_SAU_2019_pota_children_fed.png", res = 300, width = 5.5, height = 5, units = "in")  
  pota_2019 %>%
   # filter (nutrient != "Protein") %>%
    ggplot (aes (x = nutrient, y = children_fed / 1000000, fill = nutrient)) +
    geom_col() +
    theme_bw() +
    labs (x = "", y = "") +
    theme (axis.text.x = element_blank (),
           axis.text.y = element_text (size = 15),
           legend.position = "none")
  
  dev.off()

```


```{r trade_levers}
z <- sau_2019 %>%
  filter (country == "Peru", species == "Dosidicus gigas") %>%
  left_join (exports_5yr_mean, by = c("species", "country")) %>%
  replace_na (list(mn_prop_exp = 0)) %>%
  group_by (species) %>%
  summarise (foreign_catch = sum (tonnes[fishing_entity != "Peru"]),
             domestic_catch = sum (tonnes[fishing_entity == "Peru"]) * (1-mn_prop_exp),
             exported = sum (tonnes[fishing_entity == "Peru"]) * mn_prop_exp) %>%
  # creating many repeats, not sure why
  # warning about reframe()
  distinct () %>%
  # pivot longer
  pivot_longer (foreign_catch:exported,
                names_to = "lever",
                values_to = "catch_mt") %>%
  mutate (children_fed = pmap (list (species = species, amount = catch_mt, country_name = "Peru"), calc_children_fed_func)) %>%
  unnest (cols = c(children_fed)) %>%
  rename (mt = catch_mt)

z$lever <- factor (z$lever, levels = c ("exported", "foreign_catch", "domestic_catch"))

Selenium <- FALSE
if (Selenium == TRUE) {omit_nutrients <- "Protein"} else {omit_nutrients <- c("Protein", "Selenium")}


#png ("Figures/Peru_trade_levers_squid.png", width = 5, height = 4, unit = "in", res = 300)
 z %>%
  filter (!nutrient %in% omit_nutrients) %>%
  group_by (nutrient, lever) %>%
  summarise (children_fed = sum (children_fed, na.rm = TRUE)) %>%
  ggplot (aes (y = children_fed/1000000, x = reorder(nutrient, -children_fed), fill = lever)) +
  geom_col () +
  theme_bw()+
  scale_fill_grey(start = 0.8, end = 0.2) +
  labs (y = "Child RNIs met, millions", x = "", fill = "Policy lever") +
  ggtitle ("Allocative losses, trade/foreign catch") +
  theme ( 
    axis.text.y = element_text (size = 11),
    axis.text.x = element_text (size = 11),
    axis.title = element_text (size = 16),
    legend.text = element_text (size = 11),
    legend.title = element_text (size = 13),
    plot.title = element_text (size = 18),
    legend.position = c(0.8, 0.8))
 #dev.off()
 
 # print percentages
exports_5yr_mean %>% filter (country == "Peru", species == "Dosidicus gigas")

b <- sau_2019 %>%
  filter (country == "Peru", species == "Dosidicus gigas") %>%
  left_join (exports_5yr_mean, by = c("species", "country")) %>%
  replace_na (list(mn_prop_exp = 0)) %>%
  group_by (species) %>%
  summarise (foreign_catch = sum (tonnes[fishing_entity != "Peru"]),
             domestic_catch = sum (tonnes[fishing_entity == "Peru"]) * (1-mn_prop_exp),
             exported = sum (tonnes[fishing_entity == "Peru"]) * mn_prop_exp) %>%
  # creating many repeats, not sure why
  # warning about reframe()
  distinct ()
 

# which fishing nations?
sau_2019 %>%
    filter (country == "Peru", species == "Dosidicus gigas") %>%
  group_by(fishing_entity) %>%
  summarise (tot = sum (tonnes))
```

```{r end_use_levers}

c <- sau_2019 %>%
   filter (country == "Peru", species == "Dosidicus gigas") %>%
 
   group_by (species, end_use_type) %>%
   summarise (catch_mt = sum (tonnes, na.rm = TRUE)) %>%

   mutate (children_fed = pmap (list (species = species, amount = catch_mt, country_name = "Peru"), calc_children_fed_func)) %>%
   unnest (cols = c(children_fed)) %>%
   rename (mt = catch_mt)
 
 c$end_use_type <- factor (c$end_use_type, levels = c ("Fishmeal and fish oil", "Other", "Direct human consumption"))
 
 #if (Selenium == TRUE) {omit_nutrients <- "Protein"} else {omit_nutrients <- c("Protein", "Selenium")}
 png ("Figures/Peru_enduse_levers_squid.png", width = 5, height = 4, unit = "in", res = 300)
 c %>%
   filter (!nutrient %in% omit_nutrients, !is.na (end_use_type)) %>%
   group_by (nutrient, end_use_type) %>%
   summarise (children_fed = sum (children_fed, na.rm = TRUE)) %>%
   ggplot (aes (x = reorder(nutrient, -children_fed), y = children_fed/1000000, fill = end_use_type)) +
   geom_col () +
   theme_bw()+
   scale_fill_grey(start = 0.8, end = 0.2) +
   labs (y = "Child RNIs met, millions", x = "", fill = "Policy lever") +
   ggtitle ("Allocative losses, end uses") +
   theme ( 
     axis.text.y = element_text (size = 11),
     axis.text.x = element_text (size = 11),
     axis.title = element_text (size = 16),
     legend.text = element_text (size = 11),
     legend.title = element_text (size = 13),
     plot.title = element_text (size = 18),
     legend.position = c(0.8, 0.8))
 
dev.off()

c %>% filter (nutrient == "Zinc")
c %>% filter (nutrient == "Omega_3")

```

```{r nutricast_ts}
ds_spp <- readRDS("Data/Free_etal_proj_smaller.Rds")


dat <- ds_spp%>% 
    filter (country == "Peru", species == "Dosidicus gigas", year  >2030)
  
  dat$scenario <- factor (dat$scenario, levels = c ("No Adaptation", "Productivity Only", "Full Adaptation"))
  
  p <- dat %>% ggplot (aes (x = year, y = catch_mt/1000, col = scenario)) +
    geom_line() +
    theme_bw() +
    facet_grid (~ rcp, scales = "free_y") +
    labs (x = "", y = "Catch, metric tons (1000s)", col = "Mgmt scenario") +
    ggtitle ("Free et al. (2020) projections for D. gigas") +
    theme (plot.title = element_text (size = 14),
           axis.text = element_text (size = 12))

  png ("Figures/Peru_squid_nutricast_ts.png", res = 300, width = 12, height = 5, units = "in")  
  print (p) +
    theme(strip.text = element_text (size = 12),
          legend.title = element_text (size = 13),
          legend.text = element_text (size = 11),
          axis.title = element_text (size = 14))
  dev.off()
  
  
  
# samuel asked for the full time series  
  
  dat <- ds_spp%>% 
    filter (country == "Peru", species == "Dosidicus gigas")
  
  dat$scenario <- factor (dat$scenario, levels = c ("No Adaptation", "Productivity Only", "Full Adaptation"))
  
  p <- dat %>% ggplot (aes (x = year, y = catch_mt/1000, col = scenario)) +
    geom_line() +
    theme_bw() +
    facet_grid (~ rcp, scales = "free_y") +
    labs (x = "", y = "Catch, metric tons (1000s)", col = "Mgmt scenario") +
    ggtitle ("Free et al. (2020) projections for D. gigas") +
    theme (plot.title = element_text (size = 14),
           axis.text = element_text (size = 12))

  png ("Figures/Peru_squid_nutricast_ts_2020.png", res = 300, width = 12, height = 5, units = "in")  
  print (p) +
    theme(strip.text = element_text (size = 12),
          legend.title = element_text (size = 13),
          legend.text = element_text (size = 11),
          axis.title = element_text (size = 14))
  dev.off()
  
  # also zoom in on midcentury
  
  png ("Figures/Peru_squid_nutricast_ts_midcentury.png", res = 300, width = 12, height = 5, units = "in")  
  dat %>% 
    filter (year %in% 2051:2060) %>%
    ggplot (aes (x = year, y = catch_mt/1000, col = scenario)) +
    geom_line() +
    theme_bw() +
    facet_grid (~ rcp, scales = "free_y") +
    labs (x = "", y = "Catch, metric tons (1000s)", col = "Mgmt scenario") +
    ggtitle ("Free et al. (2020) projections for D. gigas, mid-century") +
    theme (plot.title = element_text (size = 14),
           axis.text = element_text (size = 12))
  dev.off()
  
   png ("Figures/Peru_squid_nutricast_ts_endcentury.png", res = 300, width = 12, height = 5, units = "in")  
  dat %>% 
    filter (year %in% 2091:2100) %>%
    ggplot (aes (x = year, y = catch_mt/1000, col = scenario)) +
    geom_line() +
    theme_bw() +
    facet_grid (~ rcp, scales = "free_y") +
    labs (x = "", y = "Catch, metric tons (1000s)", col = "Mgmt scenario") +
    ggtitle ("Free et al. (2020) projections for D. gigas, end-century") +
    theme (plot.title = element_text (size = 14),
           axis.text = element_text (size = 12))
  dev.off()
  
```
```{r nutricast profit ts}
ds_squid_long <- ds_spp%>% 
    filter (country == "Peru", species == "Dosidicus gigas") %>%
  pivot_longer(range_km2:ffmsy, 
               names_to = "variable",
               values_to = "value")
  
  ds_squid_long$scenario <- factor (ds_squid_long$scenario, levels = c ("No Adaptation", "Productivity Only", "Full Adaptation"))
  
  ds_squid_long$variable <- factor (ds_squid_long$variable, levels = c ("biomass_mt", "catch_mt", "profits_usd", "range_km2", "msy_mt", "bbmsy", "ffmsy"))

  png ("Figures/Peru_squid_nutricast_ts_2020_allvar.png", res = 300, width = 12, height = 6, units = "in") 
  p <- ds_squid_long %>% 
    filter (variable %in% c ("catch_mt", "biomass_mt", "profits_usd")) %>%
    ggplot (aes (x = year, y = value/1000000, col = scenario)) +
    geom_line () +
    facet_grid (variable ~ rcp, scales = "free_y") +
    theme_bw() +
    labs (x = "", y = "") +
    ggtitle (paste0 ("Free et al. (2020) projections, all variables (millions)")) +
    theme (plot.title = element_text (size = 14),
           axis.text = element_text (size = 12))
  print(p)
  dev.off()

```

```{r nutrient_upside}
squid_upside_nutr <- sau_2019 %>%
  filter(country == "Peru", species == "Dosidicus gigas") %>%
  group_by (country, species) %>%
  summarise (total_tonnes = sum (tonnes)) %>%
  ungroup() %>%
  left_join (catch_upside_relative, by = c("country", "species")) %>%
  mutate (# multiply ratio by current landings
    across(bau_ratio_midcentury:adapt_ratio_endcentury, ~.x * total_tonnes),
    #convert to upside, subtract 
    mey_2050 = mey_ratio_midcentury - bau_ratio_midcentury,
    mey_2100 = mey_ratio_endcentury - bau_ratio_endcentury,
    adapt_2050 = adapt_ratio_midcentury - bau_ratio_midcentury,
    adapt_2100 = adapt_ratio_endcentury - bau_ratio_endcentury) %>%
  
  select (country, rcp, species, mey_2050:adapt_2100) %>%
  pivot_longer(mey_2050:adapt_2100, 
               names_to = c("scenario", "period"),
               names_sep = "_",
               values_to = "tonnes")  %>%
    # get rid of non-matching species, NAs
    filter (!is.na (rcp)) %>%
    # convert to nutrients
    mutate (children_fed = pmap (list (species = species, amount = tonnes, country_name = country), calc_children_fed_func)) %>%
    unnest(cols = c(children_fed),  names_repair = "check_unique") 
  
  
  # fix ratios
squid_upside_nutr$scenario <- factor(squid_upside_nutr$scenario, levels = c ("mey", "adapt"))

png ("Figures/Peru_nutricast_upside_squid_allRCPs_midcentury.png", width = 13, height = 7, units= "in", res = 300)
squid_upside_nutr %>%
  filter (period == "2050") %>%
    # preliminary plot
    ggplot (aes (x = reorder(nutrient, -children_fed), y = children_fed/1000000, fill = scenario)) +
    geom_col (position = "dodge") +
    geom_hline (yintercept = 0, lty = 2) +
    facet_wrap (~rcp) +
    theme_bw() +
    # roughly match colors from gaines et al
    scale_fill_manual (values = c ("mediumseagreen", "dodgerblue4"), labels = c("Productivity Only", "Full Adaptation")) +
    labs (y = "Change in # children fed, millions", x = "", fill = "Management \nstrategy") +
    ggtitle ("Nutrition upside from climate-adaptive management, midcentury") +
    theme (strip.text = element_text (size = 12),
          legend.title = element_text (size = 13),
          legend.text = element_text (size = 11),
          axis.title = element_text (size = 14),
         axis.text = element_text (size = 12),
         plot.title = element_text (size = 16))
  
dev.off()

png ("Figures/Peru_nutricast_upside_squid_allRCPs_endcentury.png", width = 13, height = 7, units= "in", res = 300)
squid_upside_nutr %>%
  filter (period == "2100") %>%
    # preliminary plot
    ggplot (aes (x = reorder(nutrient, -children_fed), y = children_fed/1000000, fill = scenario)) +
    geom_col (position = "dodge") +
    geom_hline (yintercept = 0, lty = 2) +
    facet_wrap (~rcp) +
    theme_bw() +
    # roughly match colors from gaines et al
    scale_fill_manual (values = c ("mediumseagreen", "dodgerblue4"), labels = c("Productivity Only", "Full Adaptation")) +
    labs (y = "Change in # children fed, millions", x = "", fill = "Management \nstrategy") +
    ggtitle ("Nutrition upside from climate-adaptive management, 2100") +
  theme (strip.text = element_text (size = 12),
          legend.title = element_text (size = 13),
          legend.text = element_text (size = 11),
          axis.title = element_text (size = 14),
         axis.text = element_text (size = 12),
         plot.title = element_text (size = 16))
  
dev.off()



#display value
squid_upside_nutr %>% filter (nutrient == "Zinc")

# display percent yield?
pri_spp_catch_upside <- ds_spp %>% 
  filter(country == "Peru", species == "Dosidicus gigas") %>%
  mutate (
    period = case_when (
      year %in% c(2026:2035) ~ "2026-2035",
      year %in% c(2051:2060) ~ "2051-2060",
      year %in% c(2091:2100) ~ "2091-2100"
    )) %>%
  filter (!is.na (catch_mt), !is.na (period), scenario %in% c("No Adaptation", "Productivity Only", "Full Adaptation")) %>%
  #take mean projected catch for the decade period
  group_by (country, rcp, period, species, scenario) %>%
  summarise (catch_mt = mean (catch_mt)) %>%
  ungroup() %>%
  # find difference among scenarios--absolute and percent diff
  group_by (country, rcp, period, species) %>%
  summarize (mey_diff_mt = catch_mt[scenario == "Productivity Only"] - catch_mt[scenario == "No Adaptation"],
             mey_diff_percent = (catch_mt[scenario == "Productivity Only"] - catch_mt[scenario == "No Adaptation"])/catch_mt[scenario == "No Adaptation"] * 100,
             adapt_diff_mt = catch_mt[scenario == "Full Adaptation"] - catch_mt[scenario == "No Adaptation"],
             adapt_diff_percent = (catch_mt[scenario == "Full Adaptation"] - catch_mt[scenario == "No Adaptation"])/catch_mt[scenario == "No Adaptation"] * 100) %>%
  ungroup()


pri_spp_catch_upside %>% filter (period == "2051-2060")
```

